In [3]:
import requests
from selenium import webdriver
import math

# Функция преобразования номера тайла в координаты широты и долготы
def num2deg(xtile, ytile, zoom):
    n = 2.0 ** zoom
    lon_deg = xtile / n * 360.0 - 180.0
    lat_rad = math.atan(math.sinh(math.pi * (1 - 2 * ytile / n)))
    lat_deg = math.degrees(lat_rad)
    return (lat_deg, lon_deg)

In [47]:
# в данном сегменте с помощью вебдрайвера открывается сайт satbeams с помощью гугла и ставится зум в значчение k(max = 7), так как нам
# нам нужны тайлы с определнным зумированием/разбиением. Далее оберну в функцию, пока тесты

import time
from webdriver_manager.chrome import ChromeDriverManager
driver = webdriver.Chrome(ChromeDriverManager().install())
driver.get("https://www.satbeams.com/footprints")
k = 2  
# Maximize the window and let code stall 
# for 10s to properly maximise the window.
driver.maximize_window()
time.sleep(3)
  
# Obtain button by link text and click.
button = driver.find_element_by_css_selector("#map > div.leaflet-control-container > div.leaflet-top.leaflet-left > div.leaflet-control-zoom.leaflet-bar.leaflet-control > a.leaflet-control-zoom-in")
for i in range(k):
    button.click()
    time.sleep(3)
    
# button.click()
# time.sleep(3)
# button.click()
# time.sleep(3)
page_source = driver.page_source

[WDM] - ====== WebDriver manager ======
[WDM] - Current google-chrome version is 111.0.5563
[WDM] - Get LATEST chromedriver version for 111.0.5563 google-chrome
[WDM] - Driver [C:\Users\glebk\.wdm\drivers\chromedriver\win32\111.0.5563.64\chromedriver.exe] found in cache


In [11]:
page_source

'<html itemscope="" itemtype="http://schema.org/WebSite" class=" ext-strict"><head><style>.cesium-credit-lightbox-overlay {display: none; z-index: 1; position: absolute; top: 0; left: 0; width: 100%; height: 100%; background-color: rgba(80, 80, 80, 0.8);  }\n.cesium-credit-lightbox {background-color: #303336; color: #ffffff; position: relative; min-height: 100px; margin: auto;  }\n.cesium-credit-lightbox > ul > li a, .cesium-credit-lightbox > ul > li a:visited {color: #ffffff;  }\n.cesium-credit-lightbox > ul > li a:hover {color: #48b;  }\n.cesium-credit-lightbox.cesium-credit-lightbox-expanded {border: 1px solid #444; border-radius: 5px; max-width: 370px;  }\n.cesium-credit-lightbox.cesium-credit-lightbox-mobile {height: 100%; width: 100%;  }\n.cesium-credit-lightbox-title {padding: 20px 20px 0 20px;  }\n.cesium-credit-lightbox-close {font-size: 18pt; cursor: pointer; position: absolute; top: 0; right: 6px; color: #ffffff;  }\n.cesium-credit-lightbox-close:hover {color: #48b;  }\n.ces

In [66]:
# тут достаю сслыки на все спутники

import requests
from bs4 import BeautifulSoup
import numpy as np

soup = BeautifulSoup(page_source, 'html.parser')
button_next = driver.find_element_by_css_selector('#sat_bar > div:nth-child(3)')
links = soup.find_all('a', {'class':'sat_div satellite_gray'}, href=True)
hrefs = np.array([])
hr = np.array([])
a = True
while a == True:
    page_source = driver.page_source
    soup = BeautifulSoup(page_source, 'html.parser')
    # print(soup)    
    links = soup.find_all('a', {'class':'sat_div satellite_gray'}, href=True)
    for link in links:
        hr = np.append(hr,link.get('href'))
#         hr.append(link.get('href'))
    if all(elem in hrefs for elem in hr):
        a = False
    else:
        result = np.in1d(hr, hrefs)
        hrefs = np.append(hrefs,hr[result==False])
        
    button_next.click()
    time.sleep(1)
# divs = soup.select('div.paint')

# for div in divs:
#     print(div.text)

D:\anaconda\envs\MLEnv\lib\site-packages\ipykernel_launcher.py:21: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison


In [67]:
hrefs

array(['?position=284', '?position=285', '?position=286', '?position=287',
       '?position=288', '?position=290', '?position=293', '?position=295',
       '?position=297', '?position=299', '?position=302', '?position=305',
       '?position=306', '?position=307', '?position=310', '?position=313',
       '?position=315', '?position=317', '?position=320', '?position=323',
       '?position=324', '?position=326', '?position=328', '?position=330',
       '?position=331', '?position=333', '?position=335', '?position=336',
       '?position=338', '?position=340', '?position=342', '?position=344',
       '?position=345', '?position=346', '?position=348', '?position=349',
       '?position=350', '?position=352', '?position=353', '?position=355',
       '?position=356', '?position=357', '?position=2', '?position=3',
       '?position=5', '?position=7', '?position=9', '?position=10',
       '?position=11', '?position=13', '?position=16', '?position=17',
       '?position=19', '?position=20', '

array([1., 1., 2., 3., 1., 2., 3., 1.])

array([ True, False])

array([4])